### PR TITLE
Add RSA signing option, support only python3

### PR DESCRIPTION
**Pull request by jservidio**
This change is [Reviewable](https://reviewable.io/reviews/SpirentCom/pymakeself/2)

### CODE REVIEW

**Comment by jservidio** [comment]
In addition to adding RSA signing to our forked repo, this PR includes most of the changes from the March 10, 2022 and Oct 15, 2024 commits to https://github.com/gammazero/pymakeself/commits/main.  I omitted any changes that require a minimum of python 3.12, as well as a current bug (bad python2/python3 check) in https://github.com/gammazero/pymakeself/blob/main/pymakeself/aes/aesctr.py#L23.

**Review by lwheat — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SpirentCom/pymakeself/2)* status: all files reviewed, 5 unresolved discussions (waiting on @jservidio)

___
*[`pymakeself/makeself.py` line 158 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9VjyuC3UKJZ29M-cT:-OC9VjyuC3UKJZ29M-cU:bqwpp2d) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L158)):*
> ```Python
>             # Unpack the rsa tarfile then delete it.
>             with tarfile.open(rsa_path) as t:
>                 t.extractall(tmp_dir) #, filter='tar')
> ```

If the stuff after the pound sign is a comment (looks like it), it ought to be removed. The formatting makes it look like part of the arg list
___
*[`pymakeself/makeself.py` line 323 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9Zi_B3--QTCAqAoPB:-OC9Zi_B3--QTCAqAoPC:bstq1fg) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L323)):*
> ```Python
>     add_digital_signature = False
>     if priv_key_file:
>         if not os.path.isfile(priv_key_file):
> ```

Ought to do command line arg error checking in main() with the rest of the arg processing.
___
*[`pymakeself/makeself.py` line 393 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9XjqS2KQFOZqQ8Unm:-OC9XjqT5SWuOXTWYPPI:b-o8bq07) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L393)):*
> ```Python
>         shutil.copytree(os.path.join(parent_path, dir_name),
>                         os.path.join(dst_dir, dir_name))
> ```

If pymakeself is invoked with both a password and public/private keys, looks like it's create an aes directory and an rsa directory. Are they supposed to be mutually exclusive?
___
*[`pymakeself/makeself.py` line 646 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9ZEV-073QBvY_3t_g:-OC9ZEV-073QBvY_3t_h:b-9zuneh) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L646)):*
> ```Python
>     passwd = None
>     pw_str = None
>     priv_key_str = None
> ```

Ought to move the initialization of this near the conditional
___
*[`pymakeself/makeself.py` line 658 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9YqzLE8prkHtLeC6F:-OC9YqzLE8prkHtLeC6G:b-2dddw9) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L658)):*
> ```Python
>     if args.priv_key_file:
>         priv_key_str = '<specified, not shown>'
> ```

Are encrypting and public/private signing mutually exclusive? The file handling seems to point in that direction. If so, the arg processing should enforce it.

**Review by jservidio — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/SpirentCom/pymakeself/2)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @lwheat)

___
*[`pymakeself/makeself.py` line 158 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9VjyuC3UKJZ29M-cT:-OCeArYo5xTQwl_trryE:b-896fix) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L158)):*
<details><summary><i>Previously, lwheat (Lee Wheat) wrote…</i></summary><blockquote>

If the stuff after the pound sign is a comment (looks like it), it ought to be removed. The formatting makes it look like part of the arg list
</blockquote></details>

Done.
___
*[`pymakeself/makeself.py` line 323 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9Zi_B3--QTCAqAoPB:-OCeAtNc2wM4fiVi-jQr:b-896fix) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L323)):*
<details><summary><i>Previously, lwheat (Lee Wheat) wrote…</i></summary><blockquote>

Ought to do command line arg error checking in main() with the rest of the arg processing.
</blockquote></details>

Done.
___
*[`pymakeself/makeself.py` line 393 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9XjqS2KQFOZqQ8Unm:-OCeAvjM0cecEj35m97J:b1065da) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L393)):*
<details><summary><i>Previously, lwheat (Lee Wheat) wrote…</i></summary><blockquote>

If pymakeself is invoked with both a password and public/private keys, looks like it's create an aes directory and an rsa directory. Are they supposed to be mutually exclusive?
</blockquote></details>

Confirmed that having both encryption/password and public/private keys works.
___
*[`pymakeself/makeself.py` line 646 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9ZEV-073QBvY_3t_g:-OCeBZux0DXZ4rrAupkg:b-896fix) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L646)):*
<details><summary><i>Previously, lwheat (Lee Wheat) wrote…</i></summary><blockquote>

Ought to move the initialization of this near the conditional
</blockquote></details>

Done.
___
*[`pymakeself/makeself.py` line 658 at r1](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-OC9YqzLE8prkHtLeC6F:-OCeBa4j9Mkbq24uHlvB:b1065da) ([raw file](https://github.com/SpirentCom/pymakeself/blob/3d20391553c0e54c58db5f6d191be725aff1b2b8/pymakeself/makeself.py#L658)):*
<details><summary><i>Previously, lwheat (Lee Wheat) wrote…</i></summary><blockquote>

Are encrypting and public/private signing mutually exclusive? The file handling seems to point in that direction. If so, the arg processing should enforce it.
</blockquote></details>

Confirmed that having both encryption/password and public/private keys works.

**Review by lwheat — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SpirentCom/pymakeself/2#-:-OCeFKAL3FDhQUwubXuX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jservidio)

**Pull request merged**
